google/tachometer

CHANGELOG.md
src/cli.ts
src/format.ts

Example of what's generated:
<table><tr><th align="right">Benchmark</th><td>shack</td></tr><tr><th align="right">Variant</th><td></td></tr><tr><th align="right">Impl</th><td>lit-html</td></tr><tr><th align="right">Version</th><td>default</td></tr><tr><th align="right">Sample size</th><td>2</td></tr><tr><th align="right">Bytes</th><td>110.36&nbsp;KiB</td></tr></table>
<table>
<tr><th>Browser</th><th>Runtime [95% CI]</th><th>StdDev (CV)</th><th>Slowdown [95% CI]</th><th>Relative [95% CI]</th><th>Direction</th></tr>
<tr><td>Chrome&nbsp;Headless&nbsp;74.0.3729.108</td><td>[4.336ms,&nbsp;21.299ms]</td><td>0.94ms&nbsp;(7%)</td><td>N/A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>N/A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td>baseline</td></tr><tr><td>Firefox&nbsp;60.0</td …

GitHub Check report is now formatted as HTML instead of ASCII.

---

CHANGELOG.md
README.md
client/src/bench.ts
package-lock.json
src/browser.ts
src/cli.ts
src/server.ts
src/specs.ts
src/types.ts

- Adds `--measure=fcp` flag which measures [First Contentful Paint](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint) time. This works by calling the [Performance Timeline API](https://developer.mozilla.org/en-US/docs/Web/API/Performance_Timeline) from webdriver. These paint events are currently only available in Chrome.
- In this mode, you don't need to call `bench.start()` and `bench.stop()` anymore (you can, but it will have no effect).
- Removed the `--paint` flag (which wasn't really documented), since this supersedes it. Since this works by calling a client script, we don't actually need to use Chrome logs at all.
- Also includes some refactoring relating to the fact that we previously always assumed that we'd be getting a callback from the page. We …

Support measuring First Contentful Paint (FCP)

---

CHANGELOG.md
README.md
client/src/bench.ts
src/cli.ts
src/format.ts
src/server.ts
src/specs.ts
src/test/specs_test.ts
src/types.ts

- Entirely removes the notion of variants. Instead, you can now specify query params when specifying the benchmarks to run (e.g. `tach my-benchmark?foo=bar`).
- Remove a bunch of information from `--manual` mode output. This added a bunch of complexity, since in manual mode we don't know in advance which benchmark we're running, so we had to pass and receive more information to the browser so that we can figure that out when a result comes in. But it's not worth it, since manual mode should have very limited usage anyway, since it offers no statistical significance.
- Add `--version` flag (fixes https://github.com/PolymerLabs/tachometer/issues/33)
- Add a little more unit test coverage (more in a future PR).

Replace variants with querystrings

---

CHANGELOG.md
src/cli.ts
src/server.ts
src/test/data/mylib/package.json
src/test/versions_test.ts
src/types.ts
src/versions.ts

This PR does preparation work for dropping the implementation concept, and the file layout requirements, which will come in the next PR.
1) Previously we installed custom NPM package versions to:
`<your project>/<implementation>/versions/<label>`
Now we install to:
`<system temp dir>/tachometer/versions/<sha256(implementation dir, label)>`
This way we won't litter your directories with temporary files, which was already not great, but would be even worse when we're pointing tachometer at arbitrary directories on your system.
2) We now run a separate server for each custom NPM installation. With the fixed file layout, we could guarantee a unique URL path for each benchmark for each NPM installation, since we mount them to `/benchmarks/<implementation>/versions/<version>/<benchmark>`. But …

Prepare for dropping file layout requirements

---

CHANGELOG.md
src/cli.ts
src/github.ts

Fixes https://github.com/Polymer/tachometer/issues/41
Will allow us to tell the difference between PR vs branch Tachometer runs.

Support label in GitHub check JSON object.

---

CHANGELOG.md
package-lock.json
package.json
src/cli.ts
src/config.ts
src/test/config_test.ts

Automatically update config files with a $schema property, pointing to
the JSON schema for the file on unpkg. This will provide in-editor
contextual help for many IDEs (like VS Code) when writing
tachometer config files.

Update config files with reference to the schema, if absent.

---

CHANGELOG.md
package-lock.json
package.json
src/server.ts

If you run `npx foo`, it will:
1) Find and run the binary called `foo` in your nearest `node_modules/.bin` (no matter what package it comes from).
2) If the binary wasn't found, temporarily install the latest package `foo` and run its binary (no matter what its binary name is).
In our case, `tach` is our binary, but `tachometer` is our package, and `tach` is a totally unrelated package.
So, if you already have `tachometer` installed, `npx tach` works fine. But if you don't, it will install `tach` (the wrong package), and then fail because package `tach` has no binary (or worse, run a malicious package).
Even weirder, if `tachometer` *is* installed, but you run `npx tachometer`, then it won't notice that `tachometer` is already installed (since for step 1 it only checks the binary name), …

Add tachometer bin alias, some minor tweaks, and release 0.4.3

---

CHANGELOG.md
package.json
src/server.ts

Getting some noisy debug logging with default logging options due to:
https://github.com/Polymer/koa-node-resolve/issues/16
https://github.com/Polymer/koa-node-resolve/issues/17
Disable for now, and release 0.4.4

Temporarily disable koa-node-resolve logging

---

config.schema.json
package-lock.json
package.json
src/cli.ts
src/config.ts

Works around an issue where IDEs may not follow redirects. This is also more correct, as it will ensure the schema matches the version of tachometer being used.

Write a versioned URL for the schema.

---

CHANGELOG.md
config.schema.json
src/browser.ts
src/cli.ts
src/config.ts
src/specs.ts
src/test/browser_test.ts
src/test/config_test.ts
src/util.ts

This adds some more structured handling of browser configuration, to prepare for the next PR which adds remote webdriver support. Progress towards https://github.com/Polymer/tachometer/issues/48
Also fixes https://github.com/Polymer/tachometer/issues/58 where only Chrome could be launched.
Also fixes a bug where exceptions wouldn't exit the process, because the server continued to listen indefinitely.
cc @sorvell

Refactor and add structure to browser handling

---

CHANGELOG.md
README.md
package.json
src/browser.ts

Fixes https://github.com/Polymer/tachometer/issues/43
Note I tried the [edgedriver](https://www.npmjs.com/package/edgedriver) package on my Windows machine, but it wasn't able to download the WebDriver plugin. This (third-party) package contains a static list of Windows build numbers, and mine was not included (https://unpkg.com/edgedriver@4.17134.1/install.js). The latest [instructions ](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) from Microsoft just give a command to run from `cmd` instead of a download URL anyway, so I've just documented that users should follow those Microsoft instructions.

Add support for Edge on Windows

---

CHANGELOG.md
README.md
src/browser.ts
src/cli.ts
src/config.ts
src/server.ts
src/test/browser_test.ts
src/test/config_test.ts

Fixes https://github.com/Polymer/tachometer/issues/48
You can now specify that a browser should be launched not from the local machine, but from a remote Selenium Standalone Server instance running on another machine.
I've tested this on my home network by running tachometer on my Mac, but launching Chrome and Edge on a remote Windows desktop.
See `READMD.md` for more details.

Add remote benchmarking support

---

CHANGELOG.md
README.md
config.schema.json
src/browser.ts
src/cli.ts
src/types.ts

Fixes https://github.com/Polymer/tachometer/issues/60.
You can now use `--measure=global` and set `window.tachometerResult = <millis>` from the benchmark script. In this mode, tachometer will poll until it finds a result, similar to how we already grab first contentful paint time.
This serves a few goals:
1) It provides a way to set arbitrary results, for when `bench.start()` and `bench.stop()` don't give enough control (e.g. forwarding some timing data from another system).
2) It provides a way to report timing data from a server other than the built-in static server. (This is currently tricky to do, since you don't know the host/port of the server that is expecting to receive the result).
3) It will be compatible with IE, since IE doesn't support ES modules or `fetch`.
In a major …

Add window.tachometerResult reporting style

---

CHANGELOG.md
src/format.ts
src/test/format_test.ts

Fixes https://github.com/Polymer/tachometer/issues/80

Don't show query params when a label is used.

---

CHANGELOG.md
src/test/versions_test.ts
src/versions.ts

Fixes https://github.com/Polymer/tachometer/issues/82
Recommend viewing with ?w=1 because the test didn't change as much as it looks.

Fix bug where nodes_modules could be mounted at URL "//node_modules"

---

CHANGELOG.md
src/cli.ts

Fixes https://github.com/Polymer/tachometer/issues/86
Before, we simply ignored timeouts, allowing the sample size to fall by one each time. In the case that all samples timed out, this caused a hard crash in code that assumed there would be at least one measurement.
Now, we retry timeouts 3 times and abort after the final attempt.
This is what will now happen if your server is down:

Retry and eventually fail after timeouts, instead of ignoring.

---

CHANGELOG.md
src/server.ts

The Koa static middleware sets the body to `undefined` on 404s, which our caching layer didn't anticipate. Turns out chrome headless doesn't make the `favicon.ico` request, so people using chrome headless (probably most people) didn't notice.
Fixes https://github.com/Polymer/tachometer/issues/105

Fix errors logged when favicon.ico (or any other file) 404s

---

CHANGELOG.md
src/config.ts
src/configfile.ts
src/defaults.ts
src/test/config_test.ts
src/test/configfile_test.ts
src/test/test_helpers.ts

Affected `--manual`, `--csv-file`, `--save`, `--force-clean-npm-install`, and `--remote-accessible-host`.
Fixes https://github.com/Polymer/tachometer/issues/116
Fixes https://github.com/Polymer/tachometer/issues/119

Fix bug where flags were ignored when using a config file

---

.travis.yml
src/test/data/window-size.html
src/test/e2e_test.ts
src/test/stats_test.ts

- Adds a macOS Travis build. It runs much slower than their Linux VMs, but otherwise seems to work great. This also adds coverage for Safari and non-headless Chrome/Firefox (since non-headless isn't working on Linux). Fixes https://github.com/Polymer/tachometer/issues/77.
- Chrome headless returns 0 for `outerWidth` and `outerHeight`, but only on macOS (confirmed locally). Switching the window size e2e test from `innerWidth` and `innerHeight` works fine. Also we now test the expected size more precisely (width is very predictable, it's just height which varies based on the extra browser chrome). Fixes https://github.com/Polymer/tachometer/issues/93. Fixes https://github.com/Polymer/tachometer/issues/104.
- Be more lenient with `bench.start`/`stop` test since `setTimeout` timing is very …

Add macOS Travis build and fix flaky tests

---

CHANGELOG.md
README.md
config.schema.json
package-lock.json
package.json
src/automatic.ts
src/browser.ts
src/config.ts
src/configfile.ts
src/defaults.ts
src/flags.ts
src/specs.ts
src/test/data/random-global.html
src/test/e2e_test.ts
src/types.ts

Adds a new `globalMeasurementExpression` configuration option that is used with `"measure": "global"` that allows overriding the default `window.tachometerResult` with an arbitrary expression.
Not entirely sure I threaded through the defaults correctly.
Fixes #130

Add support for globalMeasurementExpression. Fixes #130

---

config.schema.json
src/browser.ts
src/configfile.ts
src/test/configfile_test.ts

It uses an experimental Webdriver method (sendDevToolsCommand) to set the rate of CPU throttling. As of today it works in chrome headless mode.
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md
Fixes https://github.com/Polymer/tachometer/issues/57

Add support for CPU throttle.

---

src/automatic.ts
src/configfile.ts

We also need to add a test for testing the config file, which would have caught this (the `measurement-expression` option is only tested via flags).

Fix copying the measurementExpression when applying defaults

---

CHANGELOG.md
src/browser.ts

This appears to eliminate recent measurement problems that we have observed, where changing the order of benchmarks can significantly and reliably affect the results. It is likely noopener gives us
additional process isolation and prevents code cache sharing.

Open new tabs with noopener=yes

---

CHANGELOG.md
README.md
config.schema.json
src/browser.ts
src/configfile.ts
src/test/configfile_test.ts

Fixes https://github.com/Polymer/tachometer/issues/140
Note Chrome doesn't have a way to configure this that I could find, there seem to just be lots of CLI flags instead (which are already supported).

Add "preferences" browser JSON config for Firefox about:config settings

---

package-lock.json
package.json

Enable building on Windows machines by slightly modifying scripts in package.json to use cross-platform commands and options

Enable building on Windows

---

src/cli.ts
src/util.ts
src/versions.ts

`execFile('npm')` doesn't work on Windows 😢 But `execFile('npm.cmd')` does work 😄 So this PR introduces a little helper `runNpm` to encapsulate the logic to exec npm cross-platform.
Currently running tachometer on Windows results in UnhandledPromiseRejections being logged to console cuz the npm version check fails. Also the --package-version feature fails on Windows currently.
This PR fixes both of those issues.

Support running npm on Windows

---

README.md

Was looking at implementing something similar to `--manual` when I suddenly discovered it was already there! So just thought I'd add it to the README 😄

Document `--manual` flag in the README

---

CHANGELOG.md
src/config.ts

Windows support looks good to me! I tested the `-p` and `--root` options on Windows and they seem to work as expected so I removed the TODOs related to `--root`.

Add Windows fixes to CHANGELOG

---

src/cli.ts
src/server.ts
src/test/data/alt_npm_install_dir/node_modules/dep1/dep1-main.js
src/test/data/alt_npm_install_dir/node_modules/dep1/package.json
src/test/data/alt_npm_install_dir/package.json
src/test/server_test.ts

If the server plan includes an `npmInstall` override, use that as the `koa-node-resolve` root config instead of the server root. This change allows multiple servers running with custom package versions to resolve files local to their npm overrides.
Includes some tests that fail if the code is removed.
Fixes #137 
Requires Polymer/koa-node-resolve#28 to work on Windows

Root koa-node-resolve middleware at npmInstall root if available

---

package.json

Brings in Windows fixes for koa-node-resolve

Bump koa-node-resolve to 1.0.0-pre.7

---

.travis.yml
CHANGELOG.md
config.schema.json
package-lock.json
package.json
src/browser.ts
src/configfile.ts
src/format.ts
src/test/browser_test.ts
src/test/config_test.ts
src/test/configfile_test.ts
src/test/csv_test.ts
src/test/e2e_test.ts
src/test/flags_test.ts
src/test/format_test.ts
src/test/json-output_test.ts
src/test/server_test.ts
src/test/specs_test.ts
src/test/stats_test.ts
src/test/versions_test.ts

- Fix bug where Firefox would fail to launch properly because of a new issue where new tabs are not immediately available to webdriver for some reason.
- Fix bug where Safari would fail to launch because of a new issue where setting window dimensions without window position throws an exception.
- Refresh all dependencies.
- Get Travis passing again. Update Travis OS versions. Only test Safari on macOS because it's such a slow VM, and it takes forever, often timing out. We have coverage of Chrome/Firefox already on the Linux VM.
- Prepare to release 0.4.19

Fix Firefox/Safari open/resize bugs, housekeeping, release 0.4.19

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/automatic.ts
src/config.ts
src/csv.ts
src/flags.ts
src/json-output.ts
src/manual.ts
src/test/config_test.ts
src/test/csv_test.ts
src/test/json-output_test.ts

- Added `--csv-file-raw` flag, which outputs a CSV file containing all raw sample measurements in milliseconds. Columns are benchmarks, rows are samples. First row is a header column with benchmark names. For example:
```
foo, bar, baz
1.2, 5.5, 9.4
1.8, 5.6, 9.1
1.3, 5.2, 9.8
```
- Added `samples` output to the existing JSON file output, containing the same raw sample measurements in milliseconds.
- Prepare to release `v0.4.20`.
Fixes https://github.com/Polymer/tachometer/issues/162

Add CSV/JSON output for raw samples

---

CHANGELOG.md
src/specs.ts

Fix default benchmark name on Windows to replace all `\\` with `/`. For example, previously a benchmark name might have been `"src/test\\data\\for-loop.html"`. With this fix, the benchmark name will now be `"src/test/data/for-loop.html"`.

Fix default local benchmark name on Windows

---

CHANGELOG.md
src/configfile.ts
src/defaults.ts
src/json-output.ts
src/test/json-output_test.ts

I'd like to be able to reproduce something similar to the automatic results table printed to the console from the `--json-file` output file, so this PR adds more fields to the JSON output file to enable that scenario.
I considered removing the browser field if it was just the default browser object, so I reduced some duplicate definitions of the default browser fields, but ultimately, I decided against that for simplicity. I left the de-duping though. Obviously, happy to adjust in any way you prefer!

Extend JSON output to match table printed to console

---

CHANGELOG.md
package.json

It seems some consumers run the `main` function directly (e.g. [spectrum-web-components](https://github.com/adobe/spectrum-web-components/blob/eafa852b5eb0b921129b532eb322cc71a9c9d996/test/benchmark/cli.ts#L1), [material-components-web-components](https://github.com/material-components/material-components-web-components/blob/ec11ae6e07d0e4912c2f65335e1fffa6e33f4d04/test/src/benchmark/cli.ts#L21)). Thought it may be easier for people to do this if we just fix up our "main" entry in package.json to point to `lib/cli.js` enabling `const { main } = require('tachometer');`.
Personally, I'd like this so I can do something like `require.resolve('tachometer')` to determine where tachometer is installed so I can manually run `node node_modules/tachometer/bin/tach.js` (though maybe I should just …

Fix "main" entry in package.json

---

src/automatic.ts
src/cli.ts
src/runner.ts

The main tachometer runner logic had gotten pretty hard to read. It still could be better, but this PR refactors it into a class as a start on some better organization. No behavioral changes here, just moving existing code around into methods.

Refactor main tachometer runner code into a class

---

CHANGELOG.md
README.md
config.schema.json
src/automatic.ts
src/config.ts
src/configfile.ts
src/defaults.ts
src/flags.ts
src/measure.ts
src/specs.ts
src/test/config_test.ts
src/test/configfile_test.ts
src/test/data/performance-measure.json
src/test/specs_test.ts
src/test/versions_test.ts
src/types.ts

This PR updates the internal representation of measurement types in the benchmark "spec" interface, and also adds a matching syntax that can now be used in the config file.
This is partly prep work for the next upcoming PR, which will allow specifying an *array* of measurements to take for each benchmark URL.

Improve representation of measurements

---

.travis.yml
src/install.ts

...for the sake of Node.js v10 compatibility
In Node.js v10, `module.path` is `undefined` so the `package.json` is resolved starting from the process's current working directory rather than Tachometer's install location. We don't allow on-demand installation of non-`devDependencies`, and the installation fails if `chromedriver` (et al) is not found in the ultimately resolved `package.json`.
Fixes #182

Prefer __dirname over module.path

---

CHANGELOG.md
README.md
config.schema.json
src/json-output.ts
src/measure.ts
src/runner.ts
src/test/e2e_test.ts
src/test/json-output_test.ts
src/test/test_helpers.ts
src/types.ts

This PR adds two primary features
Currently, there isn't a great way for the JSON output to match results back to the benchmark and measurement that produced those results. You'd have to parse the benchmark name (`bench [measurement]`) to determine which benchmark and which measurement these results map to.
This PR adds a `measurement` field to each benchmark result that maps to the measurement config that produced that benchmark, enabling a reporter using the JSON output a programmatic way to understand the relationship between measurements and benchmarks
This change gives the user an ability to name measurements, similar to how they can name benchmarks. This provides a way to simplify the displayed label in tables (in case the name of a window expression is long). This property is …

Add measurement object to JSON output

---

package.json

This addresses a reported and diagnosed problem caused by the Yarn package manager running package lifecycle scripts under conditions when they ordinarily would not be run by NPM (details in #186).
The strategy used to address this issue is to check for a file that is only present under conditions when we would want the `prepare` script to run: `tsconfig.json`.
Fixes #186

Fix yarn on-demand install failure

---

CHANGELOG.md
README.md
config.schema.json
src/cli.ts
src/test/versions_test.ts
src/types.ts
src/versions.ts

You can now specify a more advanced configuration for using a git repo when doing dependency swapping. This is especially useful for monorepos, as it allows installing a package that's in a sub-directory, as well as running arbitrary setup commands instead of just `prepare`.
We need this because we can't just use a simple `"git:"` style NPM dependency version specifier, because NPM assumes that the `package.json` is at the top-level of the repository (see https://github.com/npm/npm/issues/2974 for closed feature request to NPM to support sub-packages).
```json
"packageVersions": {
"label": "polyfills-master",
"dependencies": {
"@webcomponents/webcomponentsjs": {
"kind": "git",
"repo": "git@github.com:webcomponents/polyfills.git",
"ref": "master",
"subdir": "packages/webcomponentsjs", …
```

Advanced git dependency swapping for monorepos

---

CHANGELOG.md
config.schema.json
src/configfile.ts
src/test/versions_test.ts
src/types.ts
src/versions.ts

Fixes a bug with the new git dependency swapping feature, and improves temp dir caching behavior.
1. Fix error in the way we checked out git refs.
2. Always query the origin git repo and ask it to resolve refs to hashes. Use this SHA as the hash/temp directory name so that we never fall behind the origin.
3. Use the actual dependency versions to determine the identity of an NPM install directory, instead of the label.
4. Write a special file to the temp directory when installation succeeds. If the next time, we find it's not there, we assume the installation failed and re-install from scratch.
5. Simplify some code.
Fixes https://github.com/Polymer/tachometer/issues/190

Fix git checkout bug and improve dependency swapping

---

CHANGELOG.md
src/browser.ts

We launch a new browser for each unique browser configuration. However, we were not considering any of the following fields when deciding what a unique browser was: `binary`, `addArguments`, `removeArguments`, `cpuThrottlingRate` or `preferences`.

Add all browser config parameters to signature

---

CHANGELOG.md
src/versions.ts

Previously, an install error would occur if you specified a dependency substitution like this:
```js
"my-dep": {
"kind": "git",
"repo": "../",
"ref": "main",
"setupCommands": [
"npm i",
]
}
```
This happened because when `repo` is a relative path, it was getting evaluated as-is from the *temp* directory we generate for each install. Now, we first resolve such relative paths to absolute paths before install.
Fixes https://github.com/Polymer/tachometer/issues/202
cc @43081j

Resolve git file paths to absolute before npm install

---

.travis.yml
CHANGELOG.md
package-lock.json
package.json
src/format.ts
src/install.ts
src/server.ts
src/test/format_test.ts
tsconfig-base.json

- Workaround regression in `table` dependency, where you have to pass an object with numeric keys, instead of an array (fixes https://github.com/Polymer/tachometer/issues/204).
- Pin `jsonschema` dependency for now, because the latest version results in build errors and different config validation messages.
- Bump other dependencies.
- Release 0.5.6

Fix a couple of dependency regressions, release

---

package-lock.json
package.json
src/json-output.ts

The `systeminformation` package has a security vulnerability that is causing an alert to popup in my repos. This PR upgrades the dep to the fixed version. It ships with its own TS types so the additional `@types/systeminformation` package is no longer necessary.
Alternatively, we could consider removing the legacy JSON output since it is legacy. But since that is a breaking change I opt'ed for the safer PR first :) 
Replaces #208

Upgrade systeminformation for legacy JSON output

---

CHANGELOG.md
package-lock.json
package.json
src/format.ts
src/server.ts
src/versions.ts

Fixes https://github.com/Polymer/tachometer/issues/211
When doing our special git monorepo install logic, we have to resolve local relative repo paths to absolute paths, so that when we reference them from a temp directory, they are pointing to the right location. Previously we did that by assuming anything that wasn't a URL was a local path, but this is actually wrong because of repo specifiers like `git@github.com:MyOrg/my-repo.git`. Instead, now we check for `.` prefix, which is simpler and works fine because only filepaths should ever start with a `.`.
Also bump dependencies and prepare a patch release.

Detect relative local git repo paths in a more reliable way

---

CHANGELOG.md
src/runner.ts

Currently this generates filenames like `preact-local\log-auto-sample-01.json`.

Fix windows path in generated trace filenames

---

README.md
package.json

Improved the README:
- Added a table of contents.
- New introduction example that shows comparing two benchmarks, instead of just one.
- Consolidated and moved around a few sections.
- Generally improved/made more concise some of the wording.
- Fixed one or two errors/typos.
- Fixed the test status badge.
Also threw this in:
- Separate `unit` vs `e2e` tests in `package.json`.
Fixes https://github.com/Polymer/tachometer/issues/221
Fixes https://github.com/Polymer/tachometer/issues/223

Various README improvements

---

.github/workflows/tests.yaml
CHANGELOG.md
README.md
config.schema.json
src/browser.ts
src/configfile.ts

This PR adds a new `browser.profile` JSON config setting which can be used like this:
```json
{
"benchmarks": [
{
"url": "mybench.html",
"browser": {
"name": "firefox",
"profile": "/Users/<username>/Library/Application Support/Firefox/Profiles/<profile-name>"
}
}
]
}
```
It also fixes a bug where `addArguments` was not being applied to Firefox, even though it was documented that it was supported.
For Chrome, it was previously supported and documented to use `"addArguments": ["user-data-dir=<path>"]` to achieve this same effect, but I found that the equivalent for Firefox (`"-profile=<path>"`) caused Selenium to timeout trying to connect to the process. I wasn't able to figure out exactly why this was happening, but I did notice a dedicated `setProfile` method just for Firefox, which …

Add `browser.profile` setting and fix Firefox `addArguments` bug

---

.github/workflows/tests.yaml
CHANGELOG.md
README.md
package-lock.json
src/config.ts
src/configfile.ts
src/test/config_test.ts
src/test/configfile_test.ts
src/test/data/cpu-throttling-rate.json
src/test/data/measurement-expression.json
src/test/data/multiple-measurements.json
src/test/data/performance-measure.json
src/test/data/tracing-config.json
src/test/test_helpers.ts

Previously, the server root and the benchmark paths were interpreted relative to the current working directory. This meant that a given config could only ever run from one specific working directory, which was confusing and inconvenient. Now, they are interpreted relative to the config file path itself, so the current directory doesn't matter.
Also:
- Update package locks
- Remove outdated chromedriver pinning in CI
- Upgraded CI to Node 16 and the latest versions of the checkout/node actions
Fixes https://github.com/Polymer/tachometer/issues/176

Interpret paths relative to config file instead of cwd
